### ISSUE TITLE
Send a call for participation in the event for 1st-year PhDs

### ISSUE THREAD

**Issue by julbinb** [khoury-gsa/events#1]
Send a call for volunteers, maybe a form "are you interested in a new-year get-together event; if yes, would you be interested in facilitating/talking about something you wish you knew"

Step 1: send a message in Slack
Step 2: if not enough folks, defer to Sarah
Step 3: make an issue for planning the actual event

- [x] draft Slak message
- [x] send Slack message
- [x] check how many people are interested and decide the next step (Jan 4)

**Comment by julbinb** [comment]
A draft of the message for Slack:

Hi all! Would you be interested in a **virtual get-together event** before the start of the Spring semester, in January? If yes or maybe, **please indicate your interest** (yes :heavy_check_mark: maybe :zap:) and keep reading this :)

If you *would be interested in talking about your PhD experience* (e.g. things you wish you knew, lessons learned, productivity tips, etc.), *would like to facilitate a conversation*, or otherwise *interested in organizing the event*, please, click :partying_face:, reply in this thread, or email kgsa-oc@googlegroups.com. See below for the rationale behind this.

We'd like the event to be somewhat structured to make it less awkward to chat with new people, especially for 1st-year students who didn't have a proper chance to meet folks in person. One possibility is having multiple breakout rooms where somebody (maybe multiple people) facilitates the conversation or talks about their PhD experiences/answers questions as an ice-breaker. If you have any thoughts or suggestions, do let us know!

**Comment by julbinb** [comment]
[Slack message](https://khouryphds.slack.com/archives/CHZ9EQ9J8/p1609196304231500) sent.

**Comment by julbinb** [comment]
There seems to be a certain interest in the event (11 yes, 12 maybe from Slack on Jan 4), with @jethrosun and Sammie expressing interest in helping to organize the event.

My suggestion is:

1. Set up a meeting to brainstorm the event (Zoom breakout rooms, gather town, something else?)
2. Make a form to gather more information about potential participants, probably with a draft of the event format (we need to gather info about time zones, especially for first-year students, and might as well try to get feedback on the format)
3. Ask Sarah to email that form

**Comment by jethrosun** [comment]
Thank you for posting it :)

Yeah I think we can chat about it to figure out what we want to do. My current idea is: we could let the students (maybe not necessary the first year students) to select a list of topics (where we will interact and discuss in details etc) and a list of short questions (all panelists could answer but it has to be short).

Some example topics:
 - what do you think you learned from 1/2 years of course work / doing research 
 - what do you think is the part that you dislike the most about the pandemic
 - what do you think is most useful thing that you use to remain sane during the pandemic

Some example short questions:
-  what do you think is the most useful advice about doing research that you reminds yourself a lot
-  what do you think is the most important thing to keep in mind while doing a phd/research

**Comment by jethrosun** [comment]
We probably should set a time schedule and deadline per our meeting

**Comment by julbinb** [comment]
@jethrosun yep, definitely. This is currently in [this card](https://github.com/orgs/khoury-gsa/projects/9#card-52185765), and a when2meet went out.

(Feel free to convert the card to an issue for a discussion there)
