### ISSUE TITLE
Prepare a plan of the event

### ISSUE THREAD

**Issue by julbinb** [khoury-gsa/events#2]
- [x] set up when2meet for a meeting
- [x] pick time for the meeting
- [x] meet and brainstorm the event format
- [x] describe the event format
- [x] prepare a survey related to the event (time zones, ideas on a different format)
- [x] ask Sarah to send an email
- [x] possibly have a follow-up meeting
- [x] analyze the result of the survey:
  - [x] pick the date
  - [x] decide on the number of breakout rooms
  - [x] send a notification
- [x] prepare a sample list of topics to discuss
- [x] find enough facilitators
- [ ] possibly meet with facilitators prior to the event

**Comment by jethrosun** [comment]
copy paste some of the previous content for the planning meeting on Mon 01/11:

Yeah I think we can chat about it to figure out what we want to do. My current idea is: we could let the students (maybe not necessary the first year students) to select a list of topics (where we will interact and discuss in details etc) and a list of short questions (all panelists could answer but it has to be short).

Some example topics:
-  what do you think you learned from 1/2 years of course work / doing research
-  what do you think is the part that you dislike the most about the pandemic
-  what do you think is most useful thing that you use to remain sane during the pandemic

Some example short questions:
-  what do you think is the most useful advice about doing research that you reminds yourself a lot
-  what do you think is the most important thing to keep in mind while doing a phd/research

**Comment by julbinb** [comment]
I think it shouldn't be only 1st-year, but the admins asked to have 1st-years specifically in mind because they are the most isolated, didn't know anybody prior to the pandemic, etc.

**Comment by julbinb** [comment]
Based on Jan 11 meeting with Artem, Jethro, Julia, Sammie, and Sarah, the plan is:

1. Spend 10-15 min to introduce Slack and student organizations and events (Khoury Women Group, KGSA, game nights, etc.).
   We might need slides for that part.

2. Next, go to random breakout rooms to chat. There will be 2 rounds of breakout rooms, ~20 min each.

The event is going to be some time on Jan 28-30 (Thu, Fri, or Sat).

For the breakout rooms, we need facilitators who will make sure the discussion is going.
It would be good to have a sample list of topics to discuss. Probably the lists for the two rounds should not intersect, so that people can talk about new things after they switch the room. But the discussion doesn't have to be about that list of topics.

Possible additions:
- a google sheet where participants can optionally leave their names/contacts in case somebody wants to get in touch
- Zoom/internet poll at the beginning of the breakout session to start with the most burning topic

**Comment by julbinb** [comment]
The event happened :)
